### ISSUE TITLE
generatekeys.py gives incorrect key values

### ISSUE THREAD

**Issue by asm582** [SeattleTestbed/custominstallerbuilder#11] opened 2015-04-21 18:43 UTC
I was trying to regenerate cib.publickey and cib.privatekey and for some weird reason its giving me four values into the cib.publickey file.

**Comment by asm582** [comment] 2015-04-21 18:48
After looking into history of the commands that i typed below was my mistake:-

1) I did not delete the file earlier cib file that was generated by command

python generatekeys.py c~/cib 4096

2) I again generated keys without deleting the previously geenrated cib files with command as follows:-

python  generatekeys.py ~/cib 1024 

This lead to values that ever appending into the file and give weird results.

**Comment by aaaaalbert** [comment] 2015-05-01 13:15
`generatekeys`*appending* to existing key files is an issue requiring review. Please retry once more and see what you get.

**Comment by aaaaalbert** [comment] 2015-05-04 22:07
Okay, looks like we know what the issue is: Existing key files may get overwritten only partially when the keys generated later end up shorter in length than the ones in the files. Closing this one though, `generatekeys.py` belongs to softwareupdater.

New issue: SeattleTestbed/softwareupdater#53

**Closed by aaaaalbert** 2015-05-04 22:07 UTC
